### ISSUE TITLE
(Not an actual Issue) 3 and VC versions? 

### ISSUE THREAD

**Issue by ellie12134** [juicermv/GTA-GPS-Redux#10]
Hey there, Any Chance for this same Fork of the GPS Line mod but for Vice City and III? since the original Fork code originate from a version compatible with all them 3, it could be possible?

**Comment by juicermv** [comment]
The original fork is purely of the SA version. The other two have a different version which works very differently to the SA one. With this in mind, I might still port my version to those games later down the line. Closing this for now.

**Comment by juicermv** [comment]
I'm gonna re-open this for visibility.

**Comment by juicermv** [comment]
Too much work at this point. Not planned as of now.

**Comment by juicermv** [comment]
Working on this at the moment!
