### ISSUE TITLE
Parachute bug

### ISSUE THREAD

**Issue by ChapiiTikii** [juicermv/GTA-GPS-Redux#12]
When I parachute, I can't move and I keep falling at the same speed, so I end up dying from the fall, and when I disabled the mod from modloader.ini, the problem dissapears.

**Comment by juicermv** [comment]
I have encountered this issue, although I am not quite able to track down what specific piece of code is its source. I am keeping this open, for potential outside help. I'll try to track down the culprit at some point as well.

**Comment by juicermv** [comment]
This requires further testing, but this might be due to an incompatibility with a specific mod.

**Comment by juicermv** [comment]
Haven't been able to reproduce this at all.
