### ISSUE TITLE
Target distance counter

### ISSUE THREAD

**Issue by l3xrom** [juicermv/GTA-GPS-Redux#13]
Original JuniorDjjr's mod have distance counter under the radar. Some people didn't like it because of the impossibility of disabling it but for me it was very helpful. It would be cool if you add an option to enable or disable this counter in configuration .ini file.

It will be even cooler if, in addition to this, you add the ability to select a font for this counter from the fonts used by the game.

Thank you for making a good mod even better. I hope my suggestions will also be useful and easy to implement.

**Comment by l3xrom** [comment]
Damn, it would be even more ideal if you added a setting for choosing between metric and imperial units of measurement.
And another small addition to the ability to choose a font is to add the option to adjust the scale of the text of the counter.

Sorry for my english, I use google translate.

**Comment by juicermv** [comment]
It's fine lol

**Comment by juicermv** [comment]
Gonna release 1.3 in a couple of minutes! I've implemented it so you can choose between metric and imperial units for the distance counters. (there are two, one for the current mission objective and the other for the player's waypoint.)
