### ISSUE TITLE
Does not work in SAMP

### ISSUE THREAD

**Issue by Vladik01-11** [juicermv/GTA-GPS-Redux#15]
I don't know if this is related to my global modification, but if I use your GPS option for SAMP (R1), then it crashes at a certain distance from the player to the marker, I can throw off the modified Nodes, if it helps you, installed:
CLEO
SAMPFUNCS
MoonLoader
Limit Adjuster
FastmanLimitAdjuster
From the main

**Comment by juicermv** [comment]
Pretty sure I can track down what causes this, I'll check this out when I start working on the next update.

**Comment by Vladik01-11** [comment]
I managed to find out that the crash occurs due to some settings in the ini, it crashes on standard ones, and when I changed them for myself, the crashes disappeared.

**Comment by juicermv** [comment]
> I managed to find out that the crash occurs due to some settings in the ini, it crashes on standard ones, and when I changed them for myself, the crashes disappeared.

This is interesting. Which settings caused the crash?

**Comment by Vladik01-11** [comment]
It has something to do with the setup
"Respect direction of traffic = false"
I think this is due to the fact that the paths are not original

**Comment by juicermv** [comment]
This is most likely an issue with SAMP then, since the value you put in that setting goes straight into the function that generates the GPS path, a built-in ingame function. Idk how SAMP works but their implementation of that function if they use their own implementation isn't correct in this case.
