### ISSUE TITLE
Crashes game

### ISSUE THREAD

**Issue by imendezr** [juicermv/GTA-GPS-Redux#16]
The 'Junior_Djjr' version you based of this project works with no problem, but I can't use yours because it crashes when loading or starting a new game. I hope you fix it, because I really would like to use this version for story missions.

For what I can read it says something about timecycle, the only mods I have regarding that are "Skyline Timecyc" that requires "24h TimeCycle".
This is the log file:

GTA SA 1.0.0.0 US
Unhandled exception at 0x0055F617 in gta_sa.exe (+0x15f617): 0xC0000005: Access violation reading location 0xAE781E68.
    Register dump:
        EAX: 0x0177F078  EBX: 0x00000008  ECX: 0x99D04800  EDX: 0x99D04800  
        EDI: 0x00000000  ESI: 0x00000000  EBP: 0x00000009  EIP: 0x0055F617  
        ESP: 0x0177EDF8  EFL: 0x00010A57  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0177EDF8:  C4D00000 00000000 00560618 00000000 00000000 0000001F
        0x0177EE10:  00000000 0177F2FC 00000001 7ADEE97D 00000000 3F7EB852
        0x0177EE28:  00000009 25D64CD0 3F7EB850 25D64FC4 00000000 00B73710
        0x0177EE40:  00000000 00000000 3BA3D800 3BA3D70B 00000008 00000000
        0x0177EE58:  00000000 00000000 3F733334 BEE66667 00000000 021C0300
        0x0177EE70:  4ABB0188 4ABB019C 0177EF00 7734C673 00000053 00000020
        0x0177EE88:  00000000 01990000 00000000 00000000 3F800000 C47A4000
        0x0177EEA0:  05267B48 3F800000 3F800000 415CDC14 001B0000 79C5BB6B
        0x0177EEB8:  00000000 0177F11C 0F721C00 00000000 00000000 0177F10C
        0x0177EED0:  00000002 00000018 001B01C4 00000004 00000003 001B0000
        base: 0x01580000   top: 0x0177EDF8   bottom: 0x01780000
        
    Backtrace (may be wrong):
        =>0x0055F617 CTimeCycleCurrent::GetInfo+0x167 in gta_sa.exe (+0x15f617) (0x0177EDFC) 
          0x00560618 _ZN10CTimeCycle19CalcColoursForPointE7CVectorP10CColourSet+0x248 in gta_sa.exe (+0x160618)

**Comment by juicermv** [comment]
Well the mod doesn't call the function listed in the backtrace at any point and generally doesn't do anything with the timecycle. I also have 24 Hour Timecycle installed and have never encountered this issue. Do you mind providing your complete modlist?

**Comment by imendezr** [comment]
I currently have +80 mods, so to avoid giving you a giant list I was removing mods to see which was conflicting with yours and I found it.
It's "GraphicsTweaker", I mostly use it to make the game brighter because my timecyc mod makes the game very dark, notably in the nights.

As I mentioned early, the base GPS Line Mod is compatible with GraphicsTweaker. I don't know what changes have you done to it but I appreciate if you fix it.

**Comment by imendezr** [comment]
https://www.mixmods.com.br/2022/09/graphicstweaker/

This is the link to the mod mentioned.

**Comment by juicermv** [comment]
Right so this is most likely an issue with GraphicsTweaker as it directly modifies the timecycle. Closing this for now.
