### ISSUE TITLE
Unlock after "Monster" mission

### ISSUE THREAD

**Issue by Wanoca** [juicermv/GTA-GPS-Redux#17]
Someone suggested and I agree that it might be worth creating a setting in the .ini to unlock the mod during and after the "Monster" mission where CJ is introduced to the GPS.
>You got a GPS in the cab. Get to each set of map coordinates as quick as you can...
>First, what's a GPS? Second, fail what?

**Comment by juicermv** [comment]
You can do this yourself if you want to. I never really thought this explanation made much sense anyway since you have blips and navigation markers from the start of the game. They're only acknowledged in-lore in that specific mission.
