### ISSUE TITLE
you might want to disable gps route in racing mission + driving school and while in the boat

### ISSUE THREAD

**Issue by Sanscode1937** [juicermv/GTA-GPS-Redux#19]
because its seems pretty useless in racing and driving school cuz u already know where to go, and while drivin a boat its useful maybe but, yeah its kinda goofy

**Comment by juicermv** [comment]
I think it'd neat during races but haven't tested it out in driving school. If enough people complain about this I'll add an option to disable it.

**Comment by ToMattBan** [comment]
I particularly liked it in the races and in the last drive-scholl challenge.
With the boat I agree it's "useless"
