### ISSUE TITLE
SA-MP Issue

### ISSUE THREAD

**Issue by CanerKaraca23** [juicermv/GTA-GPS-Redux#2]
Mod works on SA-MP only with old SAMP-GPS.asi. Can you implement a fix for SA-MP to use only your mod in SA-MP?
Also color config isn't working.
https://github.com/janglapuk/SAMP-GPS

**Comment by yoni1857** [comment]
Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.

**Comment by yoni1857** [comment]
Also please note that I don't have SA-MP installed so I have no real way to test this. If you'd like to you can test it yourself once I make the necessary changes but you'll have to manually compile this yourself.

**Comment by yoni1857** [comment]
The sa-mp branch should hopefully contain the fix, but again you'll have to compile it yourself.

**Comment by CanerKaraca23** [comment]
> Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> 
> Edit: Full color config is available as of the latest update.

![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)

You mean this? i changed as green but still same.

**Comment by CanerKaraca23** [comment]
> The sa-mp branch should hopefully contain the fix, but again you'll have to compile it yourself.

Thank you for fix, i can test it but don't know how to build it.

**Comment by yoni1857** [comment]
> > Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> > Edit: Full color config is available as of the latest update.
> 
> ![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)
> 
> You mean this? i changed as green but still same.

Can you show your config?

**Comment by CanerKaraca23** [comment]
> 

`; This applies to all GPS routes
[Navigation Config]

; Self explanatory. Can be any positive value.
Navigation line width = 2.5

; Self explanatory once again. 0/1
Enable navigation on bicycles = 0

; GTA V does not provide GPS routes for moving
; targets like cars and peds. If you'd like to
; enable navigation for these objects set this to 1. 0/1
Enable navigation for moving targets = 0

; This value sets how close you have to be before the
; navigation line stops showing. Also automatically
; removes waypoint. 
Navigation line removal proximity = 25.0


; These settings are specific to the GPS
; route following your waypoint (the manual
; target set by the player). 
[Waypoint Config]

; R color value. 0-255
Waypoint line red = 0

; G color value. 0-255
Waypoint line green = 255
 
; B color value. 0-255
Waypoint line blue = 0

; Self explanatory. 0-255
Waypoint line opacity = 255

; These settings allow you to set custom colors
; for the various navigation paths in missions.
; Each color is represented by RGBA values separated
; by , .
[Custom Colors]

; Self explanatory. 0/1
Enabled = 0

; Used for enemies.
Red = 255, 0 , 0, 255

; Used for pickups and other things.
Green = 0, 255, 0, 255

; Used for friendlies.
Blue = 0, 0, 255, 255

; Not really used as far as I've seen.
White = 255, 255, 255, 255

; Used for destinations.
Yellow = 255, 255, 0

; These two aren't really used either.
Purple = 255, 0, 255, 255
Cyan = 0, 255, 255, 255`

Here, v1.2 normal version on sa-mp (cannot compile sa-mp)

**Comment by CanerKaraca23** [comment]
> > > Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> > > Edit: Full color config is available as of the latest update.
> > 
> > 
> > ![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)
> > You mean this? i changed as green but still same.
> 
> Can you show your config?

Still same after 1.2.1.

**Comment by yoni1857** [comment]
> > > > Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> > > > Edit: Full color config is available as of the latest update.
> > > 
> > > 
> > > ![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)
> > > You mean this? i changed as green but still same.
> > 
> > 
> > Can you show your config?
> 
> Still same after 1.2.1.

Do you have the original GPS mod (not my version) installed as well by any chance? Also, in order to compile the SA-MP branch you need to install plugin-sdk. Have you ever worked with C/C++ before?

**Comment by CanerKaraca23** [comment]
> > > > > Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> > > > > Edit: Full color config is available as of the latest update.
> > > > 
> > > > 
> > > > ![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)
> > > > You mean this? i changed as green but still same.
> > > 
> > > 
> > > Can you show your config?
> > 
> > 
> > Still same after 1.2.1.
> 
> Do you have the original GPS mod (not my version) installed as well by any chance? Also, in order to compile the SA-MP branch you need to install plugin-sdk. Have you ever worked with C/C++ before?

I have SAMP-GPS.asi with your mod to be able to use your mod on SA-MP. If i delete SAMP-GPS.asi, mod is not working on SA-MP. Probably SAMP-GPS.asi overrides your mod (just a guess, i'm not developer). I don't worked with C/C++ before, don't know anything about coding. Some github programs have workflows to build anything on GitHub's actions tab. Is it possible to add to this mod? So anyone can easily download the latest build on actions tab.

**Comment by yoni1857** [comment]
> > > > > > Color config is only for your waypoint, as in the red target blip you can set manually on the map. I'll check out a potential fix for SA-MP.
> > > > > > Edit: Full color config is available as of the latest update.
> > > > > 
> > > > > 
> > > > > ![Ekran görüntüsü 2022-09-19 121724](https://user-images.githubusercontent.com/37447503/190986715-2a2b06b8-c590-4489-b1ef-a2e44d9b9350.jpg)
> > > > > You mean this? i changed as green but still same.
> > > > 
> > > > 
> > > > Can you show your config?
> > > 
> > > 
> > > Still same after 1.2.1.
> > 
> > 
> > Do you have the original GPS mod (not my version) installed as well by any chance? Also, in order to compile the SA-MP branch you need to install plugin-sdk. Have you ever worked with C/C++ before?
> 
> I have SAMP-GPS.asi with your mod to be able to use your mod on SA-MP. If i delete SAMP-GPS.asi, mod is not working on SA-MP. Probably SAMP-GPS.asi overrides your mod (just a guess, i'm not developer). I don't worked with C/C++ before, don't know anything about coding. Some github programs have workflows to build anything on GitHub's actions tab. Is it possible to add to this mod? So anyone can easily download the latest build on actions tab.

Yeah, obviously another installation of the mod that uses similar code might affect this one's functionality. Also, automatic building via actions is not possible unfortunately due to plugin-sdk requiring a very specific Visual C++ SDK that cannot be installed on actions.

**Comment by yoni1857** [comment]
I'll try to build the SA-MP version and upload it as a release.

**Comment by yoni1857** [comment]
You can find the build [here](https://github.com/yoni1857/GTA-GPS-Redux/releases/tag/SAMP-TEST)

**Comment by CanerKaraca23** [comment]
> You can find the build [here](https://github.com/yoni1857/GTA-GPS-Redux/releases/tag/SAMP-TEST)

Thank you. I tried and mod didn't worked in game.

**Comment by yoni1857** [comment]
I've released a new SAMP test build, please test it out if you can. Also reopening this issue for visibility.

https://github.com/yoni1857/GTA-GPS-Redux/releases/tag/SAMP-TEST2

**Comment by CanerKaraca23** [comment]
It works well now, thank you! Also color is green now, works perfect. Issue can be closed.

**Comment by juicermv** [comment]
Alright, no problem!
