### ISSUE TITLE
Lag stutter

### ISSUE THREAD

**Issue by Lolahh29** [juicermv/GTA-GPS-Redux#22]
Everytime when i play a mission it lags, it seems like i tracked down the bug it seems like its because its checking for the mission's position every second so it lags the game and stutters it any fixes for this.

**Comment by juicermv** [comment]
Should be fixed as of latest build (in actions)

**Comment by juicermv** [comment]
This should be fully fixed as of the latest release (1.4.4). I'd love to hear your feedback. Also, FYI it's really not because the mod checks the blip's position.
