### ISSUE TITLE
Virus Detection

### ISSUE THREAD

**Issue by CanerKaraca23** [juicermv/GTA-GPS-Redux#24]
https://www.virustotal.com/gui/file/243efb1fbe921621b04531487bfdd042a92de4d8bfe96560d5c643e43d1fec92

VirusTotal detects too much virusses. Also log disable not works.

**Comment by juicermv** [comment]
Only 9/70 vendors "detected" anything. That's completely fine. What do you mean by log disable not working? It might create the file but nothing is gonna get written. Either way I'm in the process of completely re-writing the mod so this isn't that relevant.

**Comment by CanerKaraca23** [comment]
> 

Oh, i mean completely disabling logging, not even creating .log file. Virus detection isn't problem for me but some toxic users blaming the mod even source is open.

**Comment by juicermv** [comment]
Mind showing me who's complaining about the viruses exactly? And where? Appreciate it thanks.

**Comment by CanerKaraca23** [comment]
> 

Discord mod share channels. Some toxic users scans with virustotal and complaining the mod. But the moderators warning them and sending the source code link. But some mod sharing moderators don't know what is "open source project" and removing from share list because of viruses. There is some bypass ways to get rid of virus flags on virustotal i see from other projects like this https://github.com/massgravel/Microsoft-Activation-Scripts/commit/cc4c8343c162768043ab8194abe657b2fd70b02c. But i don't know anything about coding and don't know it will suit to your mod too to get rid of virus flags. But it doesn't matter anymore because you're re-writing the mod. We can't wait your re-write new version and also please don't forget the SA-MP version. Thanks!
