### ISSUE TITLE
Route passes through locked down bridges

### ISSUE THREAD

**Issue by autocrusher** [juicermv/GTA-GPS-Redux#25]
In the early stages of the game, players do not have access to the bridges leading to the northern part of the map. However the mod ignores this and some of the routes will pass through those bridges, e.g. routes from Red County to San Fierro.

**Comment by juicermv** [comment]
Does this really matter? If you set a destination that goes to a locked area it's kinda on you anyway. The mod uses the game's built in pathfinding so blame the game I guess.

**Comment by autocrusher** [comment]
Thanks for the reply. What I said may be a little inaccurate. I'm not setting a destination to a locked area. If I remember correctly, there are stages in the game where the player is only able to access the two islands containting Los Santos and San Fierro, but not Las Venturas. This means that, in some cases (like going from Red County to San Fierro, as suggested above), routes given by the GPS system are unreasonable, as they first direct the player to Las Venturas, which is not accessible at the moment. So I guess the game developers didn't think of this problem.
