### ISSUE TITLE
CI Build

### ISSUE THREAD

**Issue by CanerKaraca23** [juicermv/GTA-GPS-Redux#27]
Maybe try something like this:

`name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Clone PluginSDK
      run: git clone https://github.com/DK22Pac/plugin-sdk %GITHUB_WORKSPACE%/pluginsdk

    - name: Build plugin
      run: msbuild -m GPSLine.sln /property:Configuration=Actions /property:Platform=X86

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GPS_Redux
        path: ${{env.GITHUB_WORKFLOW}}/GPSLine/bin`

**Comment by CanerKaraca23** [comment]
@juicermv 

Check CLEO5's solution, it uses plugin-sdk as submodule.

https://github.com/cleolibrary/CLEO5

**Comment by juicermv** [comment]
Thanks for the help lol. Got it sorted by now.
