### ISSUE TITLE
SAMP Support

### ISSUE THREAD

**Issue by CanerKaraca23** [juicermv/GTA-GPS-Redux#29]
I can test your builds if you maintain again the SAMP support.

**Comment by juicermv** [comment]
Testing is not the issue, it's a lot of extra effort to make sure it works on SAMP in the first place. If you want to, make your own fork supporting SAMP :)

**Comment by CanerKaraca23** [comment]
> Testing is not the issue, it's a lot of extra effort to make sure it works on SAMP in the first place. If you want to, make your own fork supporting SAMP :)

Ahahaha thanks, if i learn coding, my first job to do :)
