### ISSUE TITLE
Less decimals when displaying the value of units (displayDistance)

### ISSUE THREAD

**Issue by Jessyy** [juicermv/GTA-GPS-Redux#30]
Currently there are 6 decimal placed, visually for a player is a bit overkill ( if you ask me ).
![image_2024-04-08_212802615](https://github.com/juicermv/GTA-GPS-Redux/assets/2624326/7cfacf20-b17b-48fc-9634-34b35b87b8ba)

My recommendation for this situation, to have a new parameter in config that:
1.  rounds off the number to the specified value (e..g distanceDecimals = 6)
2.  for the most common (e..g distanceType = 3)
> 0 - 539m
> 1 - 539.40m
> 2 - 539.401m
> 3 - 539.401672m

**Comment by juicermv** [comment]
Addressed this in the latest commit :) I don't really see anyone using anything above 3 decimal places and even that's redundant really so unless there's considerable pushback at the moment it's gonna be 1, and only on Mile/Kilometer distance.

**Comment by juicermv** [comment]
Addressed in [d3b6254](https://github.com/juicermv/GTA-GPS-Redux/commit/d3b6254bd459fc4677d4e89966426eec5e947192).
