### ISSUE TITLE
Broken road ways of traffic

### ISSUE THREAD

**Issue by shadowM88** [juicermv/GTA-GPS-Redux#31]
This issue happen when i load my save with this script. All traffic ride to side when stay roadblocks.
![gallery3](https://github.com/juicermv/GTA-GPS-Redux/assets/171092368/e6224303-0cdf-4dac-8134-c1292e853c04)

**Comment by juicermv** [comment]
Thanks for moving this to a separate issue! This mod does not modify anything related to traffic or NPC behavior. This is either an incompatibility with one of the other mods installed or completely unrelated to GPS Redux.
