### ISSUE TITLE
Paradiso bug

### ISSUE THREAD

**Issue by parsafrzi** [juicermv/GTA-GPS-Redux#35]
The marker wont disappear in Paradiso/San Fierro

**Comment by parsafrzi** [comment]
Juniper hollow and calton heights too

**Comment by juicermv** [comment]
Which version of the mod are you using?

**Comment by parsafrzi** [comment]
the latest one,when i go to some places like barbara or katie's house,the marker does not remove automaticly

**Comment by parsafrzi** [comment]
> Which version of the mod are you using?

v1.4.5

**Comment by juicermv** [comment]
Try downloading [this](https://github.com/juicermv/GTA-GPS-Redux/actions/runs/9570794421/artifacts/1614247159) version. Is the issue still there with it?
