### ISSUE TITLE
Should not use traffic lane direction

### ISSUE THREAD

**Issue by JuniorDjjr** [juicermv/GTA-GPS-Redux#8]
I'm glad you're continuing this project, as it's something really important for the game.  

But the idea of respecting lane direction is terrible. This should be an option in the .ini, and disabled by default. It is only useful for people who play the game respecting the traffic laws (roleplay). And even in this case it's bad, because the game's map wasn't designed for that.  

![](https://www.mixmods.com.br/wp-content/uploads/2022/10/gta-sa-mod-gps-problem.jpg)

**Comment by juicermv** [comment]
Perhaps I could calculate both and pick the shortest one of the two (in addition to having the option to choose one or the other). Will implement.

**Comment by JuniorDjjr** [comment]
> Perhaps I could calculate both and pick the shortest one of the two (in addition to having the option to choose one or the other). Will implement.

What's the point of calculating both and finding the closest?

You would be calculating X and Y (2 lanes), and then only X (only valid dir lane), but in X and Y you have already calculated X.

That is, there is no way X and Y give a longer path than only X.

**Comment by juicermv** [comment]
I meant I calculate both and choose the one that's shortest meaning I calculate once with traffic direction enabled, and then once without it, and then pick the shortest of the two.

**Comment by JuniorDjjr** [comment]
Yes I understood that.

Traffic direction enabled: X (only correct lane)
Traffic direction disabled: XY (correct **and** incorrect lane)

If you calculate only "disabled", you are already calculated both sides, then for sure you will have the shortest way.

**Comment by juicermv** [comment]
Oh that's right lol, my mistake.

**Comment by juicermv** [comment]
Re-opening this so it shows up on the milestone thing.

**Comment by juicermv** [comment]
Added the toggle in the config but it's gonna be on by default as most people seem to prefer it that way (judging by the comments on mixmods). Releasing soon.
